GET http://localhost:8080/exist/restxq/xoai/listRecords?url=https:%2F%2Foai.openedition.org&set=journals:jtei&metadataPrefix=mets

###

GET https://oai.openedition.org/?verb=ListRecords&set=journals:jtei&metadataPrefix=mets
